export * from './Header/Header';
export * from './GenreBadge/GenreBadge';
export * from './PosterPreview/PosterPreview';
export * from './StarsRating/StarsRating';
export * from './UserInfo/UserInfo';
export * from './FindForm/FindForm'
export * from './Genres/Genres';
export * from './TrendingMovie/TrendingMovie';
export * from './MyPagination/MyPagination';
export * from './SliderMovie/SliderMovie';
export * from './MovieInfo/MovieInfo';
export * from './MoviesListCard/MoviesListCard';
export * from './MoviesList/MoviesList';
export * from './SwitcherTheme/SwitcherTheme';
export * from './Spinner/Spinner';
export * from './Error/Error';
export * from './UserInfo/UserInfo'